[versions]
agp = "8.8.0"
airbnbLottie = "6.1.0"
appcompatVersion = "1.6.1"
compiler = "4.16.0"
converterGson = "2.9.0"
dotlottieAndroid = "0.5.0"
drawerlayout = "1.2.0"
firebaseAuthVersion = "23.0.0"
firebaseBom = "33.8.0"
flexbox = "3.0.0"
glide = "4.16.0"
googleMaterialVersion = "1.10.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
loggingInterceptor = "4.9.3"
lottie = "6.0.1"
lottieVersion = "6.3.0"
material = "1.12.0"
activity = "1.9.2"
constraintlayout = "2.1.4"
materialVersion = "1.9.0"
mysqlConnectorJava = "5.1.49"
navigationFragment = "2.6.0"
navigationUi = "2.6.0"
googleGmsGoogleServices = "4.4.2"
firebaseDatabase = "21.0.0"
firebaseAuth = "23.1.0"
picasso = "2.8"
playServicesAuth = "21.1.1"
playServicesAuthVersion = "20.7.0"
lifecycleLivedataKtx = "2.6.1"
lifecycleViewmodelKtx = "2.6.1"
retrofit = "2.9.0"
recyclerview = "1.4.0"
kotlin = "1.9.24"
coreKtx = "1.15.0"
swiperefreshlayout = "1.1.0"

[libraries]

appcompat-v161 = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "compiler" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
dotlottie-android = { module = "com.github.LottieFiles:dotlottie-android", version.ref = "dotlottieAndroid" }
drawerlayout = { module = "androidx.drawerlayout:drawerlayout", version.ref = "drawerlayout" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-auth-v2300 = { module = "com.google.firebase:firebase-auth", version.ref = "firebaseAuthVersion" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
gms-play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuthVersion" }
google-material-v1100 = { module = "com.google.android.material:material", version.ref = "googleMaterialVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
lottie-v610 = { module = "com.airbnb.android:lottie", version.ref = "airbnbLottie" }
lottie-v630 = { module = "com.airbnb.android:lottie", version.ref = "lottieVersion" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material-v190 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
mysql-connector-java = { module = "mysql:mysql-connector-java", version.ref = "mysqlConnectorJava" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
firebase-database = { group = "com.google.firebase", name = "firebase-database", version.ref = "firebaseDatabase" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebaseAuth" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }
play-services-auth-v2111 = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayout" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

